backend:
  name: github
  repo: DevJPVR/decaps
  branch: main 

media_folder: public/img
public_folder: /img

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/content/home.md"
        label: "Página Inicial"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
          - { label: "Texto do Botão", name: "label", widget: "string", required: false }
          - { label: "Link do Botão", name: "link", widget: "string", required: false }
  - name: "resource"
    label: "Resources"
    folder: "src/content/resources" 
    create: true 
    slug: "{{title | slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }